// Demo data — Compliance & Operations Hub
// Dates relative to Feb 2026 for realistic compliance scenarios

export const demoDrivers = [
    {
        id: "driver-1",
        name: "Marco",
        surname: "Rossi",
        email: "marco.rossi@logisticbrain.it",
        phone: "+39 333 1234567",
        licenseNumber: "IT123456789",
        licenseType: "CE",
        licenseDeadline: new Date("2026-08-15"),
        cqcDeadline: new Date("2026-03-10"), // Expiring in 16 days!
        adrCertificate: true,
        adrDeadline: new Date("2026-04-30"),
        tachographCardDeadline: new Date("2027-01-15"),
        lastTachographDownload: new Date("2026-02-10"),
        weeklyHoursUsed: 47,
        dailyHoursUsed: 7.5,
        biweeklyHoursUsed: 82,
        lastRestStart: new Date("2026-02-21T20:00:00"),
        lastRestEnd: new Date("2026-02-22T07:00:00"),
        lastWeeklyRest: new Date("2026-02-16"),
        isAvailable: false,
        notes: "Autista senior, specializzato ADR. CQC in scadenza urgente.",
        createdAt: new Date("2023-01-15"),
        updatedAt: new Date("2026-02-22"),
    },
    {
        id: "driver-2",
        name: "Luigi",
        surname: "Ferrari",
        email: "luigi.ferrari@logisticbrain.it",
        phone: "+39 347 9876543",
        licenseNumber: "IT987654321",
        licenseType: "CE",
        licenseDeadline: new Date("2027-03-20"),
        cqcDeadline: new Date("2026-06-15"),
        adrCertificate: false,
        adrDeadline: null,
        tachographCardDeadline: new Date("2027-08-20"),
        lastTachographDownload: new Date("2026-02-01"),
        weeklyHoursUsed: 18,
        dailyHoursUsed: 4,
        biweeklyHoursUsed: 52,
        lastRestStart: new Date("2026-02-21T19:00:00"),
        lastRestEnd: new Date("2026-02-22T06:00:00"),
        lastWeeklyRest: new Date("2026-02-15"),
        isAvailable: true,
        notes: "Specializzato trasporti refrigerati, rotta Italia-Francia",
        createdAt: new Date("2023-03-10"),
        updatedAt: new Date("2026-02-22"),
    },
    {
        id: "driver-3",
        name: "Antonio",
        surname: "Bianchi",
        email: "antonio.bianchi@logisticbrain.it",
        phone: "+39 320 5551234",
        licenseNumber: "IT555123456",
        licenseType: "CE",
        licenseDeadline: new Date("2026-02-28"), // Expires in 6 days!
        cqcDeadline: new Date("2026-02-25"), // Expires in 3 days!
        adrCertificate: true,
        adrDeadline: new Date("2026-03-15"),
        tachographCardDeadline: new Date("2026-11-30"),
        lastTachographDownload: new Date("2026-01-18"), // Over 28 days - VIOLATION
        weeklyHoursUsed: 52,
        dailyHoursUsed: 8.5,
        biweeklyHoursUsed: 88, // Near biweekly limit of 90!
        lastRestStart: new Date("2026-02-21T22:00:00"),
        lastRestEnd: new Date("2026-02-22T06:30:00"), // Only 8.5h rest - VIOLATION (min 9h reduced)
        lastWeeklyRest: new Date("2026-02-09"),
        isAvailable: false,
        notes: "CRITICO: Patente e CQC in scadenza imminente. Scarico tachigrafo scaduto.",
        createdAt: new Date("2022-07-20"),
        updatedAt: new Date("2026-02-22"),
    },
    {
        id: "driver-4",
        name: "Giovanna",
        surname: "Conti",
        email: "giovanna.conti@logisticbrain.it",
        phone: "+39 366 7778899",
        licenseNumber: "IT777889900",
        licenseType: "C",
        licenseDeadline: new Date("2028-05-10"),
        cqcDeadline: new Date("2027-08-20"),
        adrCertificate: false,
        adrDeadline: null,
        tachographCardDeadline: new Date("2028-03-01"),
        lastTachographDownload: new Date("2026-02-18"),
        weeklyHoursUsed: 0,
        dailyHoursUsed: 0,
        biweeklyHoursUsed: 35,
        lastRestStart: null,
        lastRestEnd: null,
        lastWeeklyRest: new Date("2026-02-21"),
        isAvailable: true,
        notes: "Disponibile per turni extra. Tutti i documenti in regola.",
        createdAt: new Date("2024-01-08"),
        updatedAt: new Date("2026-02-22"),
    },
    {
        id: "driver-5",
        name: "Roberto",
        surname: "Marino",
        email: "roberto.marino@logisticbrain.it",
        phone: "+39 389 4445566",
        licenseNumber: "IT444556677",
        licenseType: "CE",
        licenseDeadline: new Date("2026-12-01"),
        cqcDeadline: new Date("2026-09-30"),
        adrCertificate: true,
        adrDeadline: new Date("2026-05-15"), // Expiring in ~3 months
        tachographCardDeadline: new Date("2027-06-10"),
        lastTachographDownload: new Date("2026-02-15"),
        weeklyHoursUsed: 38,
        dailyHoursUsed: 6,
        biweeklyHoursUsed: 72,
        lastRestStart: new Date("2026-02-21T18:00:00"),
        lastRestEnd: new Date("2026-02-22T06:00:00"),
        lastWeeklyRest: new Date("2026-02-15"),
        isAvailable: true,
        notes: "Specializzato trasporti eccezionali e ADR",
        createdAt: new Date("2023-09-01"),
        updatedAt: new Date("2026-02-22"),
    },
    {
        id: "driver-6",
        name: "Salvatore",
        surname: "Greco",
        email: "salvatore.greco@logisticbrain.it",
        phone: "+39 345 9991234",
        licenseNumber: "IT999123456",
        licenseType: "CE",
        licenseDeadline: new Date("2027-11-20"),
        cqcDeadline: new Date("2027-06-30"),
        adrCertificate: false,
        adrDeadline: null,
        tachographCardDeadline: new Date("2028-02-15"),
        lastTachographDownload: new Date("2026-02-20"),
        weeklyHoursUsed: 28,
        dailyHoursUsed: 5.5,
        biweeklyHoursUsed: 56,
        lastRestStart: new Date("2026-02-21T19:30:00"),
        lastRestEnd: new Date("2026-02-22T06:30:00"),
        lastWeeklyRest: new Date("2026-02-16"),
        isAvailable: true,
        notes: "Nuovo autista, periodo di prova. Tutti i documenti in regola.",
        createdAt: new Date("2025-11-01"),
        updatedAt: new Date("2026-02-22"),
    },
]

export const demoVehicles = [
    {
        id: "vehicle-1",
        plate: "GH 234 KL",
        brand: "Iveco",
        model: "Daily 35S18",
        type: "STANDARD" as const,
        maxCapacityKg: 3500,
        maxCapacityM3: 18,
        fuelType: "Diesel",
        yearOfManufacture: 2021,
        tachographType: "DIGITAL_V1" as const, // Needs V2 retrofit by Jul 2026
        tachographLastCalibration: new Date("2024-10-15"),
        lastMaintenance: new Date("2025-11-15"),
        revisionDeadline: new Date("2026-03-15"), // Expiring in 21 days
        insuranceDeadline: new Date("2026-12-31"),
        isAvailable: true,
        notes: "Tachigrafo V1 - retrofit V2 obbligatorio entro luglio 2026",
    },
    {
        id: "vehicle-2",
        plate: "EF 456 GH",
        brand: "Mercedes",
        model: "Actros 1845",
        type: "ADR" as const,
        maxCapacityKg: 24000,
        maxCapacityM3: 82,
        fuelType: "Diesel",
        yearOfManufacture: 2022,
        tachographType: "DIGITAL_V2" as const,
        tachographLastCalibration: new Date("2025-06-01"),
        lastMaintenance: new Date("2025-12-01"),
        revisionDeadline: new Date("2026-06-01"),
        insuranceDeadline: new Date("2026-12-31"),
        isAvailable: false,
        notes: "Attrezzato merci pericolose classe 3. Tachigrafo V2 installato.",
    },
    {
        id: "vehicle-3",
        plate: "IJ 789 KL",
        brand: "Volvo",
        model: "FH 460 Frigo",
        type: "FRIGO" as const,
        maxCapacityKg: 22000,
        maxCapacityM3: 78,
        fuelType: "Diesel",
        yearOfManufacture: 2023,
        tachographType: "SMART_V2" as const,
        tachographLastCalibration: new Date("2025-11-20"),
        lastMaintenance: new Date("2026-01-20"),
        revisionDeadline: new Date("2026-11-20"),
        insuranceDeadline: new Date("2026-12-31"),
        isAvailable: true,
        notes: "Temperatura: -25C / +25C. Certificato ATP valido.",
    },
    {
        id: "vehicle-4",
        plate: "MN 012 OP",
        brand: "Scania",
        model: "R 500",
        type: "ECCEZIONALE" as const,
        maxCapacityKg: 40000,
        maxCapacityM3: null,
        fuelType: "Diesel",
        yearOfManufacture: 2020,
        tachographType: "DIGITAL_V1" as const, // Needs V2 retrofit
        tachographLastCalibration: new Date("2024-08-10"),
        lastMaintenance: new Date("2025-10-10"),
        revisionDeadline: new Date("2026-02-28"), // Expires in 6 days!
        insuranceDeadline: new Date("2026-04-30"),
        isAvailable: false,
        notes: "CRITICO: Revisione in scadenza. Tachigrafo V1 - retrofit V2 urgente.",
    },
    {
        id: "vehicle-5",
        plate: "QR 345 ST",
        brand: "DAF",
        model: "XF 480",
        type: "STANDARD" as const,
        maxCapacityKg: 24000,
        maxCapacityM3: 82,
        fuelType: "Diesel",
        yearOfManufacture: 2024,
        tachographType: "SMART_V2" as const,
        tachographLastCalibration: new Date("2025-12-01"),
        lastMaintenance: new Date("2026-01-15"),
        revisionDeadline: new Date("2026-12-01"),
        insuranceDeadline: new Date("2026-12-31"),
        isAvailable: true,
        notes: null,
    },
    {
        id: "vehicle-6",
        plate: "TU 678 VZ",
        brand: "MAN",
        model: "TGX 18.510",
        type: "STANDARD" as const,
        maxCapacityKg: 24000,
        maxCapacityM3: 80,
        fuelType: "Diesel",
        yearOfManufacture: 2023,
        tachographType: "SMART_V2" as const,
        tachographLastCalibration: new Date("2025-09-15"),
        lastMaintenance: new Date("2025-12-20"),
        revisionDeadline: new Date("2026-09-15"),
        insuranceDeadline: new Date("2026-12-31"),
        isAvailable: true,
        notes: null,
    },
]

export const demoTrips = [
    {
        id: "trip-1",
        status: "IN_PROGRESS" as const,
        cargoType: "Materiali edili",
        cargoWeight: 18000,
        isInternational: false,
        isAdr: false,
        startDate: new Date("2026-02-22T06:00:00"),
        endDate: new Date("2026-02-22T18:00:00"),
        totalKm: 420,
        estimatedCost: 850,
        actualCost: null,
        fuelCost: 380,
        tollCost: 120,
        notes: "Consegna urgente cantiere Milano-Roma",
        vehicleId: "vehicle-1",
        driverId: "driver-1",
        vehicle: { plate: "GH 234 KL", brand: "Iveco", model: "Daily 35S18", type: "STANDARD" as const },
        driver: { name: "Marco", surname: "Rossi" },
        stops: [
            { id: "s1", sequenceOrder: 1, address: "Via Roma 1, Milano", city: "Milano", type: "PICKUP" as const, estimatedArrival: new Date("2026-02-22T06:00:00") },
            { id: "s2", sequenceOrder: 2, address: "Via Napoli 45, Roma", city: "Roma", type: "DELIVERY" as const, estimatedArrival: new Date("2026-02-22T14:00:00") },
        ],
        complianceCheck: {
            driverHoursOk: true,
            driverDocsOk: false, // CQC expiring soon
            vehicleDocsOk: false, // Revision expiring soon
            adrOk: true,
            overallStatus: "WARNING" as const,
            issues: ["CQC autista scade tra 16 giorni", "Revisione veicolo scade tra 21 giorni"],
        },
    },
    {
        id: "trip-2",
        status: "PLANNED" as const,
        cargoType: "Prodotti chimici ADR Classe 3",
        cargoWeight: 12000,
        isInternational: false,
        isAdr: true,
        startDate: new Date("2026-02-24T07:00:00"),
        endDate: new Date("2026-02-24T20:00:00"),
        totalKm: 580,
        estimatedCost: 1200,
        actualCost: null,
        fuelCost: 520,
        tollCost: 180,
        notes: "ADR Classe 3 - Liquidi infiammabili. Richiede autista con cert. ADR e veicolo ADR.",
        vehicleId: "vehicle-2",
        driverId: "driver-3",
        vehicle: { plate: "EF 456 GH", brand: "Mercedes", model: "Actros 1845", type: "ADR" as const },
        driver: { name: "Antonio", surname: "Bianchi" },
        stops: [
            { id: "s3", sequenceOrder: 1, address: "Zona Industriale, Torino", city: "Torino", type: "PICKUP" as const, estimatedArrival: new Date("2026-02-24T07:00:00") },
            { id: "s4", sequenceOrder: 2, address: "Porto di Napoli, Napoli", city: "Napoli", type: "DELIVERY" as const, estimatedArrival: new Date("2026-02-24T18:00:00") },
        ],
        complianceCheck: {
            driverHoursOk: false, // 88h biweekly, near limit
            driverDocsOk: false, // License expires Feb 28, CQC expires Feb 25
            vehicleDocsOk: true,
            adrOk: false, // Driver ADR ok but tachograph download overdue
            overallStatus: "CRITICAL" as const,
            issues: [
                "BLOCCANTE: CQC autista scade il 25/02 (prima della partenza)",
                "BLOCCANTE: Patente autista scade il 28/02",
                "Ore bisettimanali autista: 88h/90h - quasi al limite",
                "Scarico tachigrafo autista scaduto (ultimo: 18/01)",
            ],
        },
    },
    {
        id: "trip-3",
        status: "PLANNED" as const,
        cargoType: "Prodotti alimentari refrigerati",
        cargoWeight: 20000,
        isInternational: true,
        isAdr: false,
        startDate: new Date("2026-02-25T05:00:00"),
        endDate: new Date("2026-02-26T22:00:00"),
        totalKm: 1240,
        estimatedCost: 2800,
        actualCost: null,
        fuelCost: 1100,
        tollCost: 420,
        notes: "Internazionale Italia-Francia. CMR obbligatoria. Catena del freddo.",
        vehicleId: "vehicle-3",
        driverId: "driver-2",
        vehicle: { plate: "IJ 789 KL", brand: "Volvo", model: "FH 460 Frigo", type: "FRIGO" as const },
        driver: { name: "Luigi", surname: "Ferrari" },
        stops: [
            { id: "s5", sequenceOrder: 1, address: "Mercato Ortofrutticolo, Bologna", city: "Bologna", type: "PICKUP" as const, estimatedArrival: new Date("2026-02-25T05:00:00") },
            { id: "s6", sequenceOrder: 2, address: "Confine di Stato, Ventimiglia", city: "Ventimiglia", type: "CUSTOMS" as const, estimatedArrival: new Date("2026-02-25T12:00:00") },
            { id: "s7", sequenceOrder: 3, address: "Area di Servizio, Nizza", city: "Nizza", type: "REST_STOP" as const, estimatedArrival: new Date("2026-02-25T14:00:00") },
            { id: "s8", sequenceOrder: 4, address: "Marche de Rungis, Paris", city: "Parigi", type: "DELIVERY" as const, estimatedArrival: new Date("2026-02-26T08:00:00") },
        ],
        complianceCheck: {
            driverHoursOk: true,
            driverDocsOk: true,
            vehicleDocsOk: true,
            adrOk: true,
            overallStatus: "OK" as const,
            issues: ["CMR internazionale richiesta (da generare)", "Verificare sosta obbligatoria dopo 4h30 di guida"],
        },
    },
    {
        id: "trip-4",
        status: "COMPLETED" as const,
        cargoType: "Merce generale",
        cargoWeight: 8000,
        isInternational: false,
        isAdr: false,
        startDate: new Date("2026-02-20T08:00:00"),
        endDate: new Date("2026-02-20T17:00:00"),
        totalKm: 280,
        estimatedCost: 620,
        actualCost: 590,
        fuelCost: 280,
        tollCost: 90,
        notes: null,
        vehicleId: "vehicle-5",
        driverId: "driver-4",
        vehicle: { plate: "QR 345 ST", brand: "DAF", model: "XF 480", type: "STANDARD" as const },
        driver: { name: "Giovanna", surname: "Conti" },
        stops: [
            { id: "s9", sequenceOrder: 1, address: "Magazzino Centrale, Firenze", city: "Firenze", type: "PICKUP" as const, estimatedArrival: new Date("2026-02-20T08:00:00") },
            { id: "s10", sequenceOrder: 2, address: "Centro Distribuzione, Pisa", city: "Pisa", type: "DELIVERY" as const, estimatedArrival: new Date("2026-02-20T11:00:00") },
            { id: "s11", sequenceOrder: 3, address: "Deposito, Livorno", city: "Livorno", type: "DELIVERY" as const, estimatedArrival: new Date("2026-02-20T14:00:00") },
        ],
        complianceCheck: {
            driverHoursOk: true,
            driverDocsOk: true,
            vehicleDocsOk: true,
            adrOk: true,
            overallStatus: "OK" as const,
            issues: [],
        },
    },
    {
        id: "trip-5",
        status: "COMPLETED" as const,
        cargoType: "Macchinari industriali",
        cargoWeight: 35000,
        isInternational: false,
        isAdr: false,
        startDate: new Date("2026-02-17T07:00:00"),
        endDate: new Date("2026-02-17T19:00:00"),
        totalKm: 650,
        estimatedCost: 1800,
        actualCost: 1950,
        fuelCost: 700,
        tollCost: 250,
        notes: "Trasporto eccezionale completato con scorta tecnica",
        vehicleId: "vehicle-4",
        driverId: "driver-5",
        vehicle: { plate: "MN 012 OP", brand: "Scania", model: "R 500", type: "ECCEZIONALE" as const },
        driver: { name: "Roberto", surname: "Marino" },
        stops: [
            { id: "s12", sequenceOrder: 1, address: "Stabilimento FIAT, Torino", city: "Torino", type: "PICKUP" as const, estimatedArrival: new Date("2026-02-17T07:00:00") },
            { id: "s13", sequenceOrder: 2, address: "Porto di Genova, Genova", city: "Genova", type: "DELIVERY" as const, estimatedArrival: new Date("2026-02-17T17:00:00") },
        ],
        complianceCheck: {
            driverHoursOk: true,
            driverDocsOk: true,
            vehicleDocsOk: true,
            adrOk: true,
            overallStatus: "OK" as const,
            issues: [],
        },
    },
    {
        id: "trip-6",
        status: "PLANNED" as const,
        cargoType: "Componenti automotive",
        cargoWeight: 15000,
        isInternational: true,
        isAdr: false,
        startDate: new Date("2026-02-27T06:00:00"),
        endDate: new Date("2026-02-28T18:00:00"),
        totalKm: 980,
        estimatedCost: 2200,
        actualCost: null,
        fuelCost: 890,
        tollCost: 310,
        notes: "Internazionale Italia-Germania. CMR obbligatoria.",
        vehicleId: "vehicle-6",
        driverId: "driver-6",
        vehicle: { plate: "TU 678 VZ", brand: "MAN", model: "TGX 18.510", type: "STANDARD" as const },
        driver: { name: "Salvatore", surname: "Greco" },
        stops: [
            { id: "s14", sequenceOrder: 1, address: "Polo Logistico, Verona", city: "Verona", type: "PICKUP" as const, estimatedArrival: new Date("2026-02-27T06:00:00") },
            { id: "s15", sequenceOrder: 2, address: "Passo del Brennero", city: "Brennero", type: "CUSTOMS" as const, estimatedArrival: new Date("2026-02-27T10:00:00") },
            { id: "s16", sequenceOrder: 3, address: "Raststatte Inntal", city: "Innsbruck", type: "REST_STOP" as const, estimatedArrival: new Date("2026-02-27T12:00:00") },
            { id: "s17", sequenceOrder: 4, address: "BMW Werk, Munchen", city: "Monaco", type: "DELIVERY" as const, estimatedArrival: new Date("2026-02-27T18:00:00") },
        ],
        complianceCheck: {
            driverHoursOk: true,
            driverDocsOk: true,
            vehicleDocsOk: true,
            adrOk: true,
            overallStatus: "OK" as const,
            issues: ["CMR internazionale richiesta (da generare)", "Primo viaggio internazionale per questo autista"],
        },
    },
]

export const demoDocuments = [
    // Driver documents
    { id: "doc-1", type: "LICENSE" as const, status: "EXPIRING_SOON" as const, fileName: "Patente_Bianchi_Antonio.pdf", expirationDate: new Date("2026-02-28"), tripId: null, vehicleId: null, driverId: "driver-3", createdAt: new Date("2021-02-28") },
    { id: "doc-2", type: "CQC" as const, status: "EXPIRING_SOON" as const, fileName: "CQC_Bianchi_Antonio.pdf", expirationDate: new Date("2026-02-25"), tripId: null, vehicleId: null, driverId: "driver-3", createdAt: new Date("2021-02-25") },
    { id: "doc-3", type: "CQC" as const, status: "EXPIRING_SOON" as const, fileName: "CQC_Rossi_Marco.pdf", expirationDate: new Date("2026-03-10"), tripId: null, vehicleId: null, driverId: "driver-1", createdAt: new Date("2021-03-10") },
    { id: "doc-4", type: "ADR_CERT" as const, status: "VALID" as const, fileName: "ADR_Rossi_Marco.pdf", expirationDate: new Date("2026-04-30"), tripId: null, vehicleId: null, driverId: "driver-1", createdAt: new Date("2021-04-30") },
    { id: "doc-5", type: "ADR_CERT" as const, status: "EXPIRING_SOON" as const, fileName: "ADR_Bianchi_Antonio.pdf", expirationDate: new Date("2026-03-15"), tripId: null, vehicleId: null, driverId: "driver-3", createdAt: new Date("2021-03-15") },
    { id: "doc-6", type: "ADR_CERT" as const, status: "VALID" as const, fileName: "ADR_Marino_Roberto.pdf", expirationDate: new Date("2026-05-15"), tripId: null, vehicleId: null, driverId: "driver-5", createdAt: new Date("2021-05-15") },
    { id: "doc-7", type: "LICENSE" as const, status: "VALID" as const, fileName: "Patente_Rossi_Marco.pdf", expirationDate: new Date("2026-08-15"), tripId: null, vehicleId: null, driverId: "driver-1", createdAt: new Date("2021-08-15") },
    { id: "doc-8", type: "LICENSE" as const, status: "VALID" as const, fileName: "Patente_Ferrari_Luigi.pdf", expirationDate: new Date("2027-03-20"), tripId: null, vehicleId: null, driverId: "driver-2", createdAt: new Date("2022-03-20") },

    // Vehicle documents
    { id: "doc-9", type: "REVISION" as const, status: "EXPIRING_SOON" as const, fileName: "Revisione_GH234KL.pdf", expirationDate: new Date("2026-03-15"), tripId: null, vehicleId: "vehicle-1", driverId: null, createdAt: new Date("2025-03-15") },
    { id: "doc-10", type: "REVISION" as const, status: "EXPIRING_SOON" as const, fileName: "Revisione_MN012OP.pdf", expirationDate: new Date("2026-02-28"), tripId: null, vehicleId: "vehicle-4", driverId: null, createdAt: new Date("2025-02-28") },
    { id: "doc-11", type: "INSURANCE" as const, status: "VALID" as const, fileName: "Assicurazione_Flotta_2026.pdf", expirationDate: new Date("2026-12-31"), tripId: null, vehicleId: null, driverId: null, createdAt: new Date("2026-01-01") },

    // Trip documents
    { id: "doc-12", type: "DDT" as const, status: "VALID" as const, fileName: "DDT_2026_004.pdf", expirationDate: null, tripId: "trip-4", vehicleId: null, driverId: null, createdAt: new Date("2026-02-20") },
    { id: "doc-13", type: "DDT" as const, status: "VALID" as const, fileName: "DDT_2026_005.pdf", expirationDate: null, tripId: "trip-5", vehicleId: null, driverId: null, createdAt: new Date("2026-02-17") },
    { id: "doc-14", type: "CMR" as const, status: "MISSING" as const, fileName: "CMR_2026_003_pending.pdf", expirationDate: null, tripId: "trip-3", vehicleId: null, driverId: null, createdAt: new Date("2026-02-22") },
    { id: "doc-15", type: "CMR" as const, status: "MISSING" as const, fileName: "CMR_2026_006_pending.pdf", expirationDate: null, tripId: "trip-6", vehicleId: null, driverId: null, createdAt: new Date("2026-02-22") },
]

export const demoAlerts = [
    { id: "alert-1", type: "DOCUMENT_EXPIRY" as const, severity: "CRITICAL" as const, title: "CQC Scade Tra 3 Giorni", message: "La CQC di Antonio Bianchi scade il 25/02/2026. L'autista NON potra guidare dopo questa data. Corso di rinnovo obbligatorio (35 ore).", isRead: false, isResolved: false, createdAt: new Date("2026-02-22T08:00:00") },
    { id: "alert-2", type: "DOCUMENT_EXPIRY" as const, severity: "CRITICAL" as const, title: "Patente Scade Tra 6 Giorni", message: "La patente CE di Antonio Bianchi scade il 28/02/2026. Visita medica obbligatoria per il rinnovo.", isRead: false, isResolved: false, createdAt: new Date("2026-02-22T08:00:00") },
    { id: "alert-3", type: "VEHICLE_MAINTENANCE" as const, severity: "CRITICAL" as const, title: "Revisione Veicolo Scade Tra 6 Giorni", message: "La revisione del veicolo MN 012 OP (Scania R 500) scade il 28/02/2026. Il veicolo NON potra circolare dopo questa data.", isRead: false, isResolved: false, createdAt: new Date("2026-02-22T08:00:00") },
    { id: "alert-4", type: "DOCUMENT_EXPIRY" as const, severity: "WARNING" as const, title: "CQC Scade Tra 16 Giorni", message: "La CQC di Marco Rossi scade il 10/03/2026. Pianificare il corso di rinnovo.", isRead: false, isResolved: false, createdAt: new Date("2026-02-22T08:00:00") },
    { id: "alert-5", type: "VEHICLE_MAINTENANCE" as const, severity: "WARNING" as const, title: "Revisione Veicolo Tra 21 Giorni", message: "Revisione del veicolo GH 234 KL (Iveco Daily) in scadenza il 15/03/2026.", isRead: true, isResolved: false, createdAt: new Date("2026-02-22T08:00:00") },
    { id: "alert-6", type: "DRIVING_HOURS" as const, severity: "CRITICAL" as const, title: "Ore Bisettimanali Al Limite", message: "Antonio Bianchi: 88h/90h bisettimanali. BLOCCANTE per assegnazione nuovi viaggi fino a reset del periodo.", isRead: false, isResolved: false, createdAt: new Date("2026-02-22T09:00:00") },
    { id: "alert-7", type: "DRIVING_HOURS" as const, severity: "WARNING" as const, title: "Ore Settimanali Elevate", message: "Marco Rossi: 47h/56h settimanali (84%). Monitorare assegnazioni rimanenti.", isRead: true, isResolved: false, createdAt: new Date("2026-02-22T09:00:00") },
    { id: "alert-8", type: "DOCUMENT_EXPIRY" as const, severity: "WARNING" as const, title: "Scarico Tachigrafo Scaduto", message: "Ultimo scarico dati tachigrafo di Antonio Bianchi: 18/01/2026 (35 giorni fa). Limite: 28 giorni. Sanzione possibile.", isRead: false, isResolved: false, createdAt: new Date("2026-02-22T08:30:00") },
    { id: "alert-9", type: "VEHICLE_MAINTENANCE" as const, severity: "INFO" as const, title: "Retrofit Tachigrafo V2", message: "2 veicoli (GH 234 KL, MN 012 OP) necessitano del retrofit al tachigrafo Smart V2 entro il 01/07/2026 (Reg. UE 165/2014).", isRead: true, isResolved: false, createdAt: new Date("2026-02-20T10:00:00") },
    { id: "alert-10", type: "DOCUMENT_EXPIRY" as const, severity: "INFO" as const, title: "CMR Da Generare", message: "2 viaggi internazionali pianificati senza CMR generata (trip-3, trip-6). Documento obbligatorio prima della partenza.", isRead: true, isResolved: false, createdAt: new Date("2026-02-22T10:00:00") },
]

export const demoStats = {
    totalTrips: 6,
    activeTrips: 1,
    plannedTrips: 3,
    completedTrips: 2,
    totalDrivers: 6,
    availableDrivers: 4,
    totalVehicles: 6,
    availableVehicles: 4,
    totalKmThisMonth: 4050,
    totalCostThisMonth: 9470,
    criticalAlerts: 3,
    warningAlerts: 4,
    infoAlerts: 3,
    complianceScore: 62,
    complianceBreakdown: {
        driverDocs: 58,
        vehicleDocs: 67,
        drivingHours: 72,
        tachograph: 50,
    },
}
