// Demo data for the app when DB is not configured
export const demoDrivers = [
    {
        id: "driver-1",
        name: "Marco",
        surname: "Rossi",
        email: "marco.rossi@logisticbrain.it",
        phone: "+39 333 1234567",
        licenseNumber: "IT123456789",
        licenseDeadline: new Date("2026-08-15"),
        cqcDeadline: new Date("2025-12-31"),
        adrCertificate: true,
        adrDeadline: new Date("2025-09-30"),
        weeklyHoursUsed: 32,
        dailyHoursUsed: 7.5,
        isAvailable: false,
        notes: "Autista senior, specializzato ADR",
        createdAt: new Date("2023-01-15"),
        updatedAt: new Date(),
    },
    {
        id: "driver-2",
        name: "Luigi",
        surname: "Ferrari",
        email: "luigi.ferrari@logisticbrain.it",
        phone: "+39 347 9876543",
        licenseNumber: "IT987654321",
        licenseDeadline: new Date("2027-03-20"),
        cqcDeadline: new Date("2026-06-15"),
        adrCertificate: false,
        adrDeadline: null,
        weeklyHoursUsed: 18,
        dailyHoursUsed: 4,
        isAvailable: true,
        notes: "Specializzato trasporti refrigerati",
        createdAt: new Date("2023-03-10"),
        updatedAt: new Date(),
    },
    {
        id: "driver-3",
        name: "Antonio",
        surname: "Bianchi",
        email: "antonio.bianchi@logisticbrain.it",
        phone: "+39 320 5551234",
        licenseNumber: "IT555123456",
        licenseDeadline: new Date("2025-11-30"),
        cqcDeadline: new Date("2025-10-15"),
        adrCertificate: true,
        adrDeadline: new Date("2026-03-15"),
        weeklyHoursUsed: 42,
        dailyHoursUsed: 8.5,
        isAvailable: false,
        notes: "Patente CQC in scadenza",
        createdAt: new Date("2022-07-20"),
        updatedAt: new Date(),
    },
    {
        id: "driver-4",
        name: "Giovanna",
        surname: "Conti",
        email: "giovanna.conti@logisticbrain.it",
        phone: "+39 366 7778899",
        licenseNumber: "IT777889900",
        licenseDeadline: new Date("2028-05-10"),
        cqcDeadline: new Date("2027-08-20"),
        adrCertificate: false,
        adrDeadline: null,
        weeklyHoursUsed: 0,
        dailyHoursUsed: 0,
        isAvailable: true,
        notes: "Disponibile per turni extra",
        createdAt: new Date("2024-01-08"),
        updatedAt: new Date(),
    },
    {
        id: "driver-5",
        name: "Roberto",
        surname: "Marino",
        email: "roberto.marino@logisticbrain.it",
        phone: "+39 389 4445566",
        licenseNumber: "IT444556677",
        licenseDeadline: new Date("2026-12-01"),
        cqcDeadline: new Date("2026-04-30"),
        adrCertificate: true,
        adrDeadline: new Date("2025-11-15"),
        weeklyHoursUsed: 25,
        dailyHoursUsed: 5,
        isAvailable: true,
        notes: "Specializzato trasporti eccezionali",
        createdAt: new Date("2023-09-01"),
        updatedAt: new Date(),
    },
]

export const demoVehicles = [
    {
        id: "vehicle-1",
        plate: "AB 123 CD",
        brand: "Iveco",
        model: "Daily 35S18",
        type: "STANDARD",
        maxCapacityKg: 3500,
        maxCapacityM3: 18,
        fuelType: "Diesel",
        yearOfManufacture: 2021,
        lastMaintenance: new Date("2024-10-15"),
        revisionDeadline: new Date("2025-10-15"),
        insuranceDeadline: new Date("2025-12-31"),
        isAvailable: true,
        notes: null,
    },
    {
        id: "vehicle-2",
        plate: "EF 456 GH",
        brand: "Mercedes",
        model: "Actros 1845",
        type: "ADR",
        maxCapacityKg: 24000,
        maxCapacityM3: 82,
        fuelType: "Diesel",
        yearOfManufacture: 2022,
        lastMaintenance: new Date("2024-09-01"),
        revisionDeadline: new Date("2025-09-01"),
        insuranceDeadline: new Date("2025-12-31"),
        isAvailable: false,
        notes: "Attrezzato per merci pericolose classe 3",
    },
    {
        id: "vehicle-3",
        plate: "IJ 789 KL",
        brand: "Volvo",
        model: "FH 460 Frigo",
        type: "FRIGO",
        maxCapacityKg: 22000,
        maxCapacityM3: 78,
        fuelType: "Diesel",
        yearOfManufacture: 2023,
        lastMaintenance: new Date("2024-11-20"),
        revisionDeadline: new Date("2025-11-20"),
        insuranceDeadline: new Date("2025-12-31"),
        isAvailable: true,
        notes: "Temperatura: -25°C / +25°C",
    },
    {
        id: "vehicle-4",
        plate: "MN 012 OP",
        brand: "Scania",
        model: "R 500 Eccezionale",
        type: "ECCEZIONALE",
        maxCapacityKg: 40000,
        maxCapacityM3: null,
        fuelType: "Diesel",
        yearOfManufacture: 2020,
        lastMaintenance: new Date("2024-08-10"),
        revisionDeadline: new Date("2025-08-10"),
        insuranceDeadline: new Date("2025-12-31"),
        isAvailable: false,
        notes: "Richiede permesso speciale per ogni viaggio",
    },
    {
        id: "vehicle-5",
        plate: "QR 345 ST",
        brand: "DAF",
        model: "XF 480",
        type: "STANDARD",
        maxCapacityKg: 24000,
        maxCapacityM3: 82,
        fuelType: "Diesel",
        yearOfManufacture: 2022,
        lastMaintenance: new Date("2024-12-01"),
        revisionDeadline: new Date("2025-12-01"),
        insuranceDeadline: new Date("2025-12-31"),
        isAvailable: true,
        notes: null,
    },
]

export const demoTrips = [
    {
        id: "trip-1",
        status: "IN_PROGRESS",
        cargoType: "Materiali edili",
        cargoWeight: 18000,
        isInternational: false,
        isAdr: false,
        startDate: new Date("2026-02-18T06:00:00"),
        endDate: new Date("2026-02-18T18:00:00"),
        totalKm: 420,
        estimatedCost: 850,
        actualCost: null,
        fuelCost: 380,
        tollCost: 120,
        notes: "Consegna urgente",
        vehicleId: "vehicle-1",
        driverId: "driver-1",
        vehicle: { plate: "AB 123 CD", brand: "Iveco", model: "Daily 35S18", type: "STANDARD" },
        driver: { name: "Marco", surname: "Rossi" },
        stops: [
            { id: "s1", sequenceOrder: 1, address: "Via Roma 1, Milano", city: "Milano", type: "PICKUP", estimatedArrival: new Date("2026-02-18T06:00:00") },
            { id: "s2", sequenceOrder: 2, address: "Via Napoli 45, Roma", city: "Roma", type: "DELIVERY", estimatedArrival: new Date("2026-02-18T14:00:00") },
        ],
    },
    {
        id: "trip-2",
        status: "PLANNED",
        cargoType: "Prodotti chimici ADR",
        cargoWeight: 12000,
        isInternational: false,
        isAdr: true,
        startDate: new Date("2026-02-19T07:00:00"),
        endDate: new Date("2026-02-19T20:00:00"),
        totalKm: 580,
        estimatedCost: 1200,
        actualCost: null,
        fuelCost: 520,
        tollCost: 180,
        notes: "Classe ADR 3 - Liquidi infiammabili",
        vehicleId: "vehicle-2",
        driverId: "driver-3",
        vehicle: { plate: "EF 456 GH", brand: "Mercedes", model: "Actros 1845", type: "ADR" },
        driver: { name: "Antonio", surname: "Bianchi" },
        stops: [
            { id: "s3", sequenceOrder: 1, address: "Zona Industriale, Torino", city: "Torino", type: "PICKUP", estimatedArrival: new Date("2026-02-19T07:00:00") },
            { id: "s4", sequenceOrder: 2, address: "Porto di Napoli, Napoli", city: "Napoli", type: "DELIVERY", estimatedArrival: new Date("2026-02-19T18:00:00") },
        ],
    },
    {
        id: "trip-3",
        status: "PLANNED",
        cargoType: "Prodotti alimentari refrigerati",
        cargoWeight: 20000,
        isInternational: true,
        isAdr: false,
        startDate: new Date("2026-02-20T05:00:00"),
        endDate: new Date("2026-02-21T22:00:00"),
        totalKm: 1240,
        estimatedCost: 2800,
        actualCost: null,
        fuelCost: 1100,
        tollCost: 420,
        notes: "Viaggio internazionale - CMR obbligatoria",
        vehicleId: "vehicle-3",
        driverId: "driver-2",
        vehicle: { plate: "IJ 789 KL", brand: "Volvo", model: "FH 460 Frigo", type: "FRIGO" },
        driver: { name: "Luigi", surname: "Ferrari" },
        stops: [
            { id: "s5", sequenceOrder: 1, address: "Mercato Ortofrutticolo, Bologna", city: "Bologna", type: "PICKUP", estimatedArrival: new Date("2026-02-20T05:00:00") },
            { id: "s6", sequenceOrder: 2, address: "Confine di Stato, Ventimiglia", city: "Ventimiglia", type: "CUSTOMS", estimatedArrival: new Date("2026-02-20T12:00:00") },
            { id: "s7", sequenceOrder: 3, address: "Marché de Rungis, Paris", city: "Parigi", type: "DELIVERY", estimatedArrival: new Date("2026-02-21T20:00:00") },
        ],
    },
    {
        id: "trip-4",
        status: "COMPLETED",
        cargoType: "Merce generale",
        cargoWeight: 8000,
        isInternational: false,
        isAdr: false,
        startDate: new Date("2026-02-15T08:00:00"),
        endDate: new Date("2026-02-15T17:00:00"),
        totalKm: 280,
        estimatedCost: 620,
        actualCost: 590,
        fuelCost: 280,
        tollCost: 90,
        notes: null,
        vehicleId: "vehicle-5",
        driverId: "driver-4",
        vehicle: { plate: "QR 345 ST", brand: "DAF", model: "XF 480", type: "STANDARD" },
        driver: { name: "Giovanna", surname: "Conti" },
        stops: [
            { id: "s8", sequenceOrder: 1, address: "Magazzino Centrale, Firenze", city: "Firenze", type: "PICKUP", estimatedArrival: new Date("2026-02-15T08:00:00") },
            { id: "s9", sequenceOrder: 2, address: "Centro Distribuzione, Pisa", city: "Pisa", type: "DELIVERY", estimatedArrival: new Date("2026-02-15T11:00:00") },
            { id: "s10", sequenceOrder: 3, address: "Deposito, Livorno", city: "Livorno", type: "DELIVERY", estimatedArrival: new Date("2026-02-15T14:00:00") },
        ],
    },
    {
        id: "trip-5",
        status: "COMPLETED",
        cargoType: "Macchinari industriali",
        cargoWeight: 35000,
        isInternational: false,
        isAdr: false,
        startDate: new Date("2026-02-10T07:00:00"),
        endDate: new Date("2026-02-10T19:00:00"),
        totalKm: 650,
        estimatedCost: 1800,
        actualCost: 1950,
        fuelCost: 700,
        tollCost: 250,
        notes: "Trasporto eccezionale - scorta tecnica richiesta",
        vehicleId: "vehicle-4",
        driverId: "driver-5",
        vehicle: { plate: "MN 012 OP", brand: "Scania", model: "R 500 Eccezionale", type: "ECCEZIONALE" },
        driver: { name: "Roberto", surname: "Marino" },
        stops: [
            { id: "s11", sequenceOrder: 1, address: "Stabilimento FIAT, Torino", city: "Torino", type: "PICKUP", estimatedArrival: new Date("2026-02-10T07:00:00") },
            { id: "s12", sequenceOrder: 2, address: "Porto di Genova, Genova", city: "Genova", type: "DELIVERY", estimatedArrival: new Date("2026-02-10T17:00:00") },
        ],
    },
]

export const demoDocuments = [
    { id: "doc-1", type: "DDT", status: "VALID", fileName: "DDT_2026_001.pdf", expirationDate: null, tripId: "trip-4", vehicleId: null, driverId: null, createdAt: new Date("2026-02-15") },
    { id: "doc-2", type: "CMR", status: "VALID", fileName: "CMR_2026_003.pdf", expirationDate: null, tripId: "trip-3", vehicleId: null, driverId: null, createdAt: new Date("2026-02-18") },
    { id: "doc-3", type: "ADR_CERT", status: "EXPIRING_SOON", fileName: "ADR_Rossi_Marco.pdf", expirationDate: new Date("2025-09-30"), tripId: null, vehicleId: null, driverId: "driver-1", createdAt: new Date("2023-09-30") },
    { id: "doc-4", type: "LICENSE", status: "EXPIRING_SOON", fileName: "Patente_Bianchi_Antonio.pdf", expirationDate: new Date("2025-11-30"), tripId: null, vehicleId: null, driverId: "driver-3", createdAt: new Date("2020-11-30") },
    { id: "doc-5", type: "CQC", status: "EXPIRING_SOON", fileName: "CQC_Bianchi_Antonio.pdf", expirationDate: new Date("2025-10-15"), tripId: null, vehicleId: null, driverId: "driver-3", createdAt: new Date("2020-10-15") },
    { id: "doc-6", type: "REVISION", status: "EXPIRING_SOON", fileName: "Revisione_EF456GH.pdf", expirationDate: new Date("2025-09-01"), tripId: null, vehicleId: "vehicle-2", driverId: null, createdAt: new Date("2024-09-01") },
    { id: "doc-7", type: "INSURANCE", status: "VALID", fileName: "Assicurazione_Flotta_2025.pdf", expirationDate: new Date("2025-12-31"), tripId: null, vehicleId: "vehicle-1", driverId: null, createdAt: new Date("2025-01-01") },
    { id: "doc-8", type: "ADR_CERT", status: "EXPIRING_SOON", fileName: "ADR_Marino_Roberto.pdf", expirationDate: new Date("2025-11-15"), tripId: null, vehicleId: null, driverId: "driver-5", createdAt: new Date("2023-11-15") },
]

export const demoAlerts = [
    { id: "alert-1", type: "DOCUMENT_EXPIRY", severity: "CRITICAL", title: "CQC in Scadenza", message: "La CQC di Antonio Bianchi scade il 15/10/2025. Rinnovo urgente.", isRead: false, isResolved: false, createdAt: new Date("2026-02-15") },
    { id: "alert-2", type: "DOCUMENT_EXPIRY", severity: "WARNING", title: "Patente in Scadenza", message: "La patente di Antonio Bianchi scade il 30/11/2025.", isRead: false, isResolved: false, createdAt: new Date("2026-02-16") },
    { id: "alert-3", type: "DOCUMENT_EXPIRY", severity: "WARNING", title: "Cert. ADR in Scadenza", message: "Il certificato ADR di Marco Rossi scade il 30/09/2025.", isRead: true, isResolved: false, createdAt: new Date("2026-02-17") },
    { id: "alert-4", type: "VEHICLE_MAINTENANCE", severity: "WARNING", title: "Revisione Veicolo", message: "Revisione del veicolo EF 456 GH scade il 01/09/2025.", isRead: false, isResolved: false, createdAt: new Date("2026-02-18") },
    { id: "alert-5", type: "DRIVING_HOURS", severity: "INFO", title: "Ore Guida Settimanali", message: "Antonio Bianchi ha raggiunto 42h di guida settimanale (limite: 56h).", isRead: true, isResolved: false, createdAt: new Date("2026-02-18") },
]

export const demoStats = {
    totalTrips: 5,
    activeTrips: 1,
    plannedTrips: 2,
    completedTrips: 2,
    totalDrivers: 5,
    availableDrivers: 3,
    totalVehicles: 5,
    availableVehicles: 3,
    totalKmThisMonth: 3170,
    totalCostThisMonth: 7010,
    criticalAlerts: 1,
    warningAlerts: 3,
    complianceScore: 78,
}
